name: 'Comment Terraform Plan on PR'
description: 'Automatically comments the essential Terraform plan output on a Pull Request'
icon: check-circle
color: orange
inputs:
  output_file:
    description: 'Path to the Terraform plan output file'
    required: true
  headline:
    description: 'Headline of the comment'
    required: false
    default: "### Terraform Plan Essential Output"
runs:
  using: 'composite'
  steps:
    - run: chmod +x ${{ github.action_path }}/src/main.sh
      shell: bash
    - run: ${{ github.action_path }}/src/main.sh "${{ inputs.output_file }}" "${{ inputs.headline }}"
      shell: bash
